/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfumistaRouteImport } from './routes/perfumista'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroDeAlunosRouteImport } from './routes/cadastro-de-alunos'
import { Route as BodyogaRouteImport } from './routes/bodyoga'
import { Route as BioRouteImport } from './routes/bio'
import { Route as AgendeSuaAulaRouteImport } from './routes/agende-sua-aula'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as LojaIndexRouteImport } from './routes/loja/index'
import { Route as CursosIndexRouteImport } from './routes/cursos/index'
import { Route as BodyogaIndexRouteImport } from './routes/bodyoga.index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PedidoCodeRouteImport } from './routes/pedido/$code'
import { Route as PainelWishlistRouteImport } from './routes/painel/wishlist'
import { Route as PainelTentativasRouteImport } from './routes/painel/tentativas'
import { Route as PainelPerguntasRouteImport } from './routes/painel/perguntas'
import { Route as PainelPerfilRouteImport } from './routes/painel/perfil'
import { Route as PainelPedidosRouteImport } from './routes/painel/pedidos'
import { Route as PainelCertificadosRouteImport } from './routes/painel/certificados'
import { Route as PagamentoCodeRouteImport } from './routes/pagamento.$code'
import { Route as LojaSlugRouteImport } from './routes/loja/$slug'
import { Route as CursosSlugRouteImport } from './routes/cursos/$slug'
import { Route as CertificadoCodeRouteImport } from './routes/certificado/$code'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminSocialRouteImport } from './routes/admin/social'
import { Route as AdminReservasRouteImport } from './routes/admin/reservas'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminNotasFiscaisRouteImport } from './routes/admin/notas-fiscais'
import { Route as AdminInscritosRouteImport } from './routes/admin/inscritos'
import { Route as AdminDisponibilidadeRouteImport } from './routes/admin/disponibilidade'
import { Route as AdminDiagnosticoPagamentosRouteImport } from './routes/admin/diagnostico-pagamentos'
import { Route as AdminDiagnosticoEnvioRouteImport } from './routes/admin/diagnostico-envio'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminBroadcastRouteImport } from './routes/admin/broadcast'
import { Route as AdminAgendamentosRouteImport } from './routes/admin/agendamentos'
import { Route as AdminSiteIndexRouteImport } from './routes/admin/site.index'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin/produtos/index'
import { Route as AdminCursosIndexRouteImport } from './routes/admin/cursos/index'
import { Route as AdminConfiguracoesIndexRouteImport } from './routes/admin/configuracoes/index'
import { Route as AdminBodyogaSlidesIndexRouteImport } from './routes/admin/bodyoga-slides/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminAjudaIndexRouteImport } from './routes/admin/ajuda.index'
import { Route as PainelAulaLessonIdRouteImport } from './routes/painel/aula/$lessonId'
import { Route as ApiPublicMediaRouteImport } from './routes/api/public/media'
import { Route as ApiPublicInstagramFeedDotxmlRouteImport } from './routes/api/public/instagram-feed[.]xml'
import { Route as AdminSiteMenuRouteImport } from './routes/admin/site.menu'
import { Route as AdminProdutosIdRouteImport } from './routes/admin/produtos/$id'
import { Route as AdminConfiguracoesUsuariosRouteImport } from './routes/admin/configuracoes/usuarios'
import { Route as AdminConfiguracoesSiteRouteImport } from './routes/admin/configuracoes/site'
import { Route as AdminConfiguracoesNewsletterRouteImport } from './routes/admin/configuracoes/newsletter'
import { Route as AdminConfiguracoesMercadopagoRouteImport } from './routes/admin/configuracoes/mercadopago'
import { Route as AdminConfiguracoesMelhorEnvioRouteImport } from './routes/admin/configuracoes/melhor-envio'
import { Route as AdminConfiguracoesIntegracoesRouteImport } from './routes/admin/configuracoes/integracoes'
import { Route as AdminConfiguracoesEmailsRouteImport } from './routes/admin/configuracoes/emails'
import { Route as AdminConfiguracoesDiagnosticosRouteImport } from './routes/admin/configuracoes/diagnosticos'
import { Route as AdminConfiguracoesCupomRouteImport } from './routes/admin/configuracoes/cupom'
import { Route as AdminConfiguracoesBaseRouteImport } from './routes/admin/configuracoes/base'
import { Route as AdminConfiguracoesAsaasRouteImport } from './routes/admin/configuracoes/asaas'
import { Route as AdminBodyogaSlidesIdRouteImport } from './routes/admin/bodyoga-slides/$id'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog/$id'
import { Route as AdminAjudaSlugRouteImport } from './routes/admin/ajuda/$slug'
import { Route as AdminCursosIdEditarRouteImport } from './routes/admin/cursos/$id/editar'
import { Route as AdminCursosIdAulasRouteImport } from './routes/admin/cursos/$id/aulas'
import { Route as AdminCursosIdAulasLessonIdQuizRouteImport } from './routes/admin/cursos/$id/aulas/$lessonId/quiz'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumistaRoute = PerfumistaRouteImport.update({
  id: '/perfumista',
  path: '/perfumista',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroDeAlunosRoute = CadastroDeAlunosRouteImport.update({
  id: '/cadastro-de-alunos',
  path: '/cadastro-de-alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyogaRoute = BodyogaRouteImport.update({
  id: '/bodyoga',
  path: '/bodyoga',
  getParentRoute: () => rootRouteImport,
} as any)
const BioRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendeSuaAulaRoute = AgendeSuaAulaRouteImport.update({
  id: '/agende-sua-aula',
  path: '/agende-sua-aula',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIndexRoute = LojaIndexRouteImport.update({
  id: '/loja/',
  path: '/loja/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyogaIndexRoute = BodyogaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BodyogaRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoCodeRoute = PedidoCodeRouteImport.update({
  id: '/pedido/$code',
  path: '/pedido/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelWishlistRoute = PainelWishlistRouteImport.update({
  id: '/painel/wishlist',
  path: '/painel/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelTentativasRoute = PainelTentativasRouteImport.update({
  id: '/painel/tentativas',
  path: '/painel/tentativas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPerguntasRoute = PainelPerguntasRouteImport.update({
  id: '/painel/perguntas',
  path: '/painel/perguntas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPerfilRoute = PainelPerfilRouteImport.update({
  id: '/painel/perfil',
  path: '/painel/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPedidosRoute = PainelPedidosRouteImport.update({
  id: '/painel/pedidos',
  path: '/painel/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelCertificadosRoute = PainelCertificadosRouteImport.update({
  id: '/painel/certificados',
  path: '/painel/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoCodeRoute = PagamentoCodeRouteImport.update({
  id: '/pagamento/$code',
  path: '/pagamento/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoCodeRoute = CertificadoCodeRouteImport.update({
  id: '/certificado/$code',
  path: '/certificado/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSocialRoute = AdminSocialRouteImport.update({
  id: '/admin/social',
  path: '/admin/social',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/admin/reservas',
  path: '/admin/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/admin/posts',
  path: '/admin/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotasFiscaisRoute = AdminNotasFiscaisRouteImport.update({
  id: '/admin/notas-fiscais',
  path: '/admin/notas-fiscais',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInscritosRoute = AdminInscritosRouteImport.update({
  id: '/admin/inscritos',
  path: '/admin/inscritos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisponibilidadeRoute = AdminDisponibilidadeRouteImport.update({
  id: '/admin/disponibilidade',
  path: '/admin/disponibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticoPagamentosRoute =
  AdminDiagnosticoPagamentosRouteImport.update({
    id: '/admin/diagnostico-pagamentos',
    path: '/admin/diagnostico-pagamentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDiagnosticoEnvioRoute = AdminDiagnosticoEnvioRouteImport.update({
  id: '/admin/diagnostico-envio',
  path: '/admin/diagnostico-envio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/admin/broadcast',
  path: '/admin/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgendamentosRoute = AdminAgendamentosRouteImport.update({
  id: '/admin/agendamentos',
  path: '/admin/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSiteIndexRoute = AdminSiteIndexRouteImport.update({
  id: '/admin/site/',
  path: '/admin/site/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/admin/produtos/',
  path: '/admin/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIndexRoute = AdminCursosIndexRouteImport.update({
  id: '/admin/cursos/',
  path: '/admin/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesIndexRoute = AdminConfiguracoesIndexRouteImport.update({
  id: '/admin/configuracoes/',
  path: '/admin/configuracoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBodyogaSlidesIndexRoute = AdminBodyogaSlidesIndexRouteImport.update({
  id: '/admin/bodyoga-slides/',
  path: '/admin/bodyoga-slides/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAjudaIndexRoute = AdminAjudaIndexRouteImport.update({
  id: '/admin/ajuda/',
  path: '/admin/ajuda/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAulaLessonIdRoute = PainelAulaLessonIdRouteImport.update({
  id: '/painel/aula/$lessonId',
  path: '/painel/aula/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaRoute = ApiPublicMediaRouteImport.update({
  id: '/api/public/media',
  path: '/api/public/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstagramFeedDotxmlRoute =
  ApiPublicInstagramFeedDotxmlRouteImport.update({
    id: '/api/public/instagram-feed.xml',
    path: '/api/public/instagram-feed.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSiteMenuRoute = AdminSiteMenuRouteImport.update({
  id: '/admin/site/menu',
  path: '/admin/site/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/admin/produtos/$id',
  path: '/admin/produtos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesUsuariosRoute =
  AdminConfiguracoesUsuariosRouteImport.update({
    id: '/admin/configuracoes/usuarios',
    path: '/admin/configuracoes/usuarios',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminConfiguracoesSiteRoute = AdminConfiguracoesSiteRouteImport.update({
  id: '/admin/configuracoes/site',
  path: '/admin/configuracoes/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesNewsletterRoute =
  AdminConfiguracoesNewsletterRouteImport.update({
    id: '/admin/configuracoes/newsletter',
    path: '/admin/configuracoes/newsletter',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminConfiguracoesMercadopagoRoute =
  AdminConfiguracoesMercadopagoRouteImport.update({
    id: '/admin/configuracoes/mercadopago',
    path: '/admin/configuracoes/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminConfiguracoesMelhorEnvioRoute =
  AdminConfiguracoesMelhorEnvioRouteImport.update({
    id: '/admin/configuracoes/melhor-envio',
    path: '/admin/configuracoes/melhor-envio',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminConfiguracoesIntegracoesRoute =
  AdminConfiguracoesIntegracoesRouteImport.update({
    id: '/admin/configuracoes/integracoes',
    path: '/admin/configuracoes/integracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminConfiguracoesEmailsRoute =
  AdminConfiguracoesEmailsRouteImport.update({
    id: '/admin/configuracoes/emails',
    path: '/admin/configuracoes/emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminConfiguracoesDiagnosticosRoute =
  AdminConfiguracoesDiagnosticosRouteImport.update({
    id: '/admin/configuracoes/diagnosticos',
    path: '/admin/configuracoes/diagnosticos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminConfiguracoesCupomRoute = AdminConfiguracoesCupomRouteImport.update({
  id: '/admin/configuracoes/cupom',
  path: '/admin/configuracoes/cupom',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesBaseRoute = AdminConfiguracoesBaseRouteImport.update({
  id: '/admin/configuracoes/base',
  path: '/admin/configuracoes/base',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesAsaasRoute = AdminConfiguracoesAsaasRouteImport.update({
  id: '/admin/configuracoes/asaas',
  path: '/admin/configuracoes/asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBodyogaSlidesIdRoute = AdminBodyogaSlidesIdRouteImport.update({
  id: '/admin/bodyoga-slides/$id',
  path: '/admin/bodyoga-slides/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/admin/blog/$id',
  path: '/admin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAjudaSlugRoute = AdminAjudaSlugRouteImport.update({
  id: '/admin/ajuda/$slug',
  path: '/admin/ajuda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIdEditarRoute = AdminCursosIdEditarRouteImport.update({
  id: '/admin/cursos/$id/editar',
  path: '/admin/cursos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIdAulasRoute = AdminCursosIdAulasRouteImport.update({
  id: '/admin/cursos/$id/aulas',
  path: '/admin/cursos/$id/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIdAulasLessonIdQuizRoute =
  AdminCursosIdAulasLessonIdQuizRouteImport.update({
    id: '/$lessonId/quiz',
    path: '/$lessonId/quiz',
    getParentRoute: () => AdminCursosIdAulasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agende-sua-aula': typeof AgendeSuaAulaRoute
  '/bio': typeof BioRoute
  '/bodyoga': typeof BodyogaRouteWithChildren
  '/cadastro-de-alunos': typeof CadastroDeAlunosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/perfumista': typeof PerfumistaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/diagnostico-envio': typeof AdminDiagnosticoEnvioRoute
  '/admin/diagnostico-pagamentos': typeof AdminDiagnosticoPagamentosRoute
  '/admin/disponibilidade': typeof AdminDisponibilidadeRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/notas-fiscais': typeof AdminNotasFiscaisRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/social': typeof AdminSocialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificado/$code': typeof CertificadoCodeRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pagamento/$code': typeof PagamentoCodeRoute
  '/painel/certificados': typeof PainelCertificadosRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/perguntas': typeof PainelPerguntasRoute
  '/painel/tentativas': typeof PainelTentativasRoute
  '/painel/wishlist': typeof PainelWishlistRoute
  '/pedido/$code': typeof PedidoCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/bodyoga/': typeof BodyogaIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/ajuda/$slug': typeof AdminAjudaSlugRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/bodyoga-slides/$id': typeof AdminBodyogaSlidesIdRoute
  '/admin/configuracoes/asaas': typeof AdminConfiguracoesAsaasRoute
  '/admin/configuracoes/base': typeof AdminConfiguracoesBaseRoute
  '/admin/configuracoes/cupom': typeof AdminConfiguracoesCupomRoute
  '/admin/configuracoes/diagnosticos': typeof AdminConfiguracoesDiagnosticosRoute
  '/admin/configuracoes/emails': typeof AdminConfiguracoesEmailsRoute
  '/admin/configuracoes/integracoes': typeof AdminConfiguracoesIntegracoesRoute
  '/admin/configuracoes/melhor-envio': typeof AdminConfiguracoesMelhorEnvioRoute
  '/admin/configuracoes/mercadopago': typeof AdminConfiguracoesMercadopagoRoute
  '/admin/configuracoes/newsletter': typeof AdminConfiguracoesNewsletterRoute
  '/admin/configuracoes/site': typeof AdminConfiguracoesSiteRoute
  '/admin/configuracoes/usuarios': typeof AdminConfiguracoesUsuariosRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/site/menu': typeof AdminSiteMenuRoute
  '/api/public/instagram-feed.xml': typeof ApiPublicInstagramFeedDotxmlRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/painel/aula/$lessonId': typeof PainelAulaLessonIdRoute
  '/admin/ajuda/': typeof AdminAjudaIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/bodyoga-slides/': typeof AdminBodyogaSlidesIndexRoute
  '/admin/configuracoes/': typeof AdminConfiguracoesIndexRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/admin/site/': typeof AdminSiteIndexRoute
  '/admin/cursos/$id/aulas': typeof AdminCursosIdAulasRouteWithChildren
  '/admin/cursos/$id/editar': typeof AdminCursosIdEditarRoute
  '/admin/cursos/$id/aulas/$lessonId/quiz': typeof AdminCursosIdAulasLessonIdQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agende-sua-aula': typeof AgendeSuaAulaRoute
  '/bio': typeof BioRoute
  '/cadastro-de-alunos': typeof CadastroDeAlunosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/perfumista': typeof PerfumistaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/diagnostico-envio': typeof AdminDiagnosticoEnvioRoute
  '/admin/diagnostico-pagamentos': typeof AdminDiagnosticoPagamentosRoute
  '/admin/disponibilidade': typeof AdminDisponibilidadeRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/notas-fiscais': typeof AdminNotasFiscaisRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/social': typeof AdminSocialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificado/$code': typeof CertificadoCodeRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pagamento/$code': typeof PagamentoCodeRoute
  '/painel/certificados': typeof PainelCertificadosRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/perguntas': typeof PainelPerguntasRoute
  '/painel/tentativas': typeof PainelTentativasRoute
  '/painel/wishlist': typeof PainelWishlistRoute
  '/pedido/$code': typeof PedidoCodeRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/bodyoga': typeof BodyogaIndexRoute
  '/cursos': typeof CursosIndexRoute
  '/loja': typeof LojaIndexRoute
  '/painel': typeof PainelIndexRoute
  '/admin/ajuda/$slug': typeof AdminAjudaSlugRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/bodyoga-slides/$id': typeof AdminBodyogaSlidesIdRoute
  '/admin/configuracoes/asaas': typeof AdminConfiguracoesAsaasRoute
  '/admin/configuracoes/base': typeof AdminConfiguracoesBaseRoute
  '/admin/configuracoes/cupom': typeof AdminConfiguracoesCupomRoute
  '/admin/configuracoes/diagnosticos': typeof AdminConfiguracoesDiagnosticosRoute
  '/admin/configuracoes/emails': typeof AdminConfiguracoesEmailsRoute
  '/admin/configuracoes/integracoes': typeof AdminConfiguracoesIntegracoesRoute
  '/admin/configuracoes/melhor-envio': typeof AdminConfiguracoesMelhorEnvioRoute
  '/admin/configuracoes/mercadopago': typeof AdminConfiguracoesMercadopagoRoute
  '/admin/configuracoes/newsletter': typeof AdminConfiguracoesNewsletterRoute
  '/admin/configuracoes/site': typeof AdminConfiguracoesSiteRoute
  '/admin/configuracoes/usuarios': typeof AdminConfiguracoesUsuariosRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/site/menu': typeof AdminSiteMenuRoute
  '/api/public/instagram-feed.xml': typeof ApiPublicInstagramFeedDotxmlRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/painel/aula/$lessonId': typeof PainelAulaLessonIdRoute
  '/admin/ajuda': typeof AdminAjudaIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/bodyoga-slides': typeof AdminBodyogaSlidesIndexRoute
  '/admin/configuracoes': typeof AdminConfiguracoesIndexRoute
  '/admin/cursos': typeof AdminCursosIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/admin/site': typeof AdminSiteIndexRoute
  '/admin/cursos/$id/aulas': typeof AdminCursosIdAulasRouteWithChildren
  '/admin/cursos/$id/editar': typeof AdminCursosIdEditarRoute
  '/admin/cursos/$id/aulas/$lessonId/quiz': typeof AdminCursosIdAulasLessonIdQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agende-sua-aula': typeof AgendeSuaAulaRoute
  '/bio': typeof BioRoute
  '/bodyoga': typeof BodyogaRouteWithChildren
  '/cadastro-de-alunos': typeof CadastroDeAlunosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/perfumista': typeof PerfumistaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/diagnostico-envio': typeof AdminDiagnosticoEnvioRoute
  '/admin/diagnostico-pagamentos': typeof AdminDiagnosticoPagamentosRoute
  '/admin/disponibilidade': typeof AdminDisponibilidadeRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/notas-fiscais': typeof AdminNotasFiscaisRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/social': typeof AdminSocialRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificado/$code': typeof CertificadoCodeRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pagamento/$code': typeof PagamentoCodeRoute
  '/painel/certificados': typeof PainelCertificadosRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/perguntas': typeof PainelPerguntasRoute
  '/painel/tentativas': typeof PainelTentativasRoute
  '/painel/wishlist': typeof PainelWishlistRoute
  '/pedido/$code': typeof PedidoCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/bodyoga/': typeof BodyogaIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/ajuda/$slug': typeof AdminAjudaSlugRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/bodyoga-slides/$id': typeof AdminBodyogaSlidesIdRoute
  '/admin/configuracoes/asaas': typeof AdminConfiguracoesAsaasRoute
  '/admin/configuracoes/base': typeof AdminConfiguracoesBaseRoute
  '/admin/configuracoes/cupom': typeof AdminConfiguracoesCupomRoute
  '/admin/configuracoes/diagnosticos': typeof AdminConfiguracoesDiagnosticosRoute
  '/admin/configuracoes/emails': typeof AdminConfiguracoesEmailsRoute
  '/admin/configuracoes/integracoes': typeof AdminConfiguracoesIntegracoesRoute
  '/admin/configuracoes/melhor-envio': typeof AdminConfiguracoesMelhorEnvioRoute
  '/admin/configuracoes/mercadopago': typeof AdminConfiguracoesMercadopagoRoute
  '/admin/configuracoes/newsletter': typeof AdminConfiguracoesNewsletterRoute
  '/admin/configuracoes/site': typeof AdminConfiguracoesSiteRoute
  '/admin/configuracoes/usuarios': typeof AdminConfiguracoesUsuariosRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/site/menu': typeof AdminSiteMenuRoute
  '/api/public/instagram-feed.xml': typeof ApiPublicInstagramFeedDotxmlRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/painel/aula/$lessonId': typeof PainelAulaLessonIdRoute
  '/admin/ajuda/': typeof AdminAjudaIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/bodyoga-slides/': typeof AdminBodyogaSlidesIndexRoute
  '/admin/configuracoes/': typeof AdminConfiguracoesIndexRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/admin/site/': typeof AdminSiteIndexRoute
  '/admin/cursos/$id/aulas': typeof AdminCursosIdAulasRouteWithChildren
  '/admin/cursos/$id/editar': typeof AdminCursosIdEditarRoute
  '/admin/cursos/$id/aulas/$lessonId/quiz': typeof AdminCursosIdAulasLessonIdQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agende-sua-aula'
    | '/bio'
    | '/bodyoga'
    | '/cadastro-de-alunos'
    | '/carrinho'
    | '/checkout'
    | '/login'
    | '/perfumista'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/agendamentos'
    | '/admin/broadcast'
    | '/admin/clientes'
    | '/admin/diagnostico-envio'
    | '/admin/diagnostico-pagamentos'
    | '/admin/disponibilidade'
    | '/admin/inscritos'
    | '/admin/notas-fiscais'
    | '/admin/pedidos'
    | '/admin/posts'
    | '/admin/reservas'
    | '/admin/social'
    | '/blog/$slug'
    | '/certificado/$code'
    | '/cursos/$slug'
    | '/loja/$slug'
    | '/pagamento/$code'
    | '/painel/certificados'
    | '/painel/pedidos'
    | '/painel/perfil'
    | '/painel/perguntas'
    | '/painel/tentativas'
    | '/painel/wishlist'
    | '/pedido/$code'
    | '/admin/'
    | '/blog/'
    | '/bodyoga/'
    | '/cursos/'
    | '/loja/'
    | '/painel/'
    | '/admin/ajuda/$slug'
    | '/admin/blog/$id'
    | '/admin/bodyoga-slides/$id'
    | '/admin/configuracoes/asaas'
    | '/admin/configuracoes/base'
    | '/admin/configuracoes/cupom'
    | '/admin/configuracoes/diagnosticos'
    | '/admin/configuracoes/emails'
    | '/admin/configuracoes/integracoes'
    | '/admin/configuracoes/melhor-envio'
    | '/admin/configuracoes/mercadopago'
    | '/admin/configuracoes/newsletter'
    | '/admin/configuracoes/site'
    | '/admin/configuracoes/usuarios'
    | '/admin/produtos/$id'
    | '/admin/site/menu'
    | '/api/public/instagram-feed.xml'
    | '/api/public/media'
    | '/painel/aula/$lessonId'
    | '/admin/ajuda/'
    | '/admin/blog/'
    | '/admin/bodyoga-slides/'
    | '/admin/configuracoes/'
    | '/admin/cursos/'
    | '/admin/produtos/'
    | '/admin/site/'
    | '/admin/cursos/$id/aulas'
    | '/admin/cursos/$id/editar'
    | '/admin/cursos/$id/aulas/$lessonId/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agende-sua-aula'
    | '/bio'
    | '/cadastro-de-alunos'
    | '/carrinho'
    | '/checkout'
    | '/login'
    | '/perfumista'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/agendamentos'
    | '/admin/broadcast'
    | '/admin/clientes'
    | '/admin/diagnostico-envio'
    | '/admin/diagnostico-pagamentos'
    | '/admin/disponibilidade'
    | '/admin/inscritos'
    | '/admin/notas-fiscais'
    | '/admin/pedidos'
    | '/admin/posts'
    | '/admin/reservas'
    | '/admin/social'
    | '/blog/$slug'
    | '/certificado/$code'
    | '/cursos/$slug'
    | '/loja/$slug'
    | '/pagamento/$code'
    | '/painel/certificados'
    | '/painel/pedidos'
    | '/painel/perfil'
    | '/painel/perguntas'
    | '/painel/tentativas'
    | '/painel/wishlist'
    | '/pedido/$code'
    | '/admin'
    | '/blog'
    | '/bodyoga'
    | '/cursos'
    | '/loja'
    | '/painel'
    | '/admin/ajuda/$slug'
    | '/admin/blog/$id'
    | '/admin/bodyoga-slides/$id'
    | '/admin/configuracoes/asaas'
    | '/admin/configuracoes/base'
    | '/admin/configuracoes/cupom'
    | '/admin/configuracoes/diagnosticos'
    | '/admin/configuracoes/emails'
    | '/admin/configuracoes/integracoes'
    | '/admin/configuracoes/melhor-envio'
    | '/admin/configuracoes/mercadopago'
    | '/admin/configuracoes/newsletter'
    | '/admin/configuracoes/site'
    | '/admin/configuracoes/usuarios'
    | '/admin/produtos/$id'
    | '/admin/site/menu'
    | '/api/public/instagram-feed.xml'
    | '/api/public/media'
    | '/painel/aula/$lessonId'
    | '/admin/ajuda'
    | '/admin/blog'
    | '/admin/bodyoga-slides'
    | '/admin/configuracoes'
    | '/admin/cursos'
    | '/admin/produtos'
    | '/admin/site'
    | '/admin/cursos/$id/aulas'
    | '/admin/cursos/$id/editar'
    | '/admin/cursos/$id/aulas/$lessonId/quiz'
  id:
    | '__root__'
    | '/'
    | '/agende-sua-aula'
    | '/bio'
    | '/bodyoga'
    | '/cadastro-de-alunos'
    | '/carrinho'
    | '/checkout'
    | '/login'
    | '/perfumista'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/agendamentos'
    | '/admin/broadcast'
    | '/admin/clientes'
    | '/admin/diagnostico-envio'
    | '/admin/diagnostico-pagamentos'
    | '/admin/disponibilidade'
    | '/admin/inscritos'
    | '/admin/notas-fiscais'
    | '/admin/pedidos'
    | '/admin/posts'
    | '/admin/reservas'
    | '/admin/social'
    | '/blog/$slug'
    | '/certificado/$code'
    | '/cursos/$slug'
    | '/loja/$slug'
    | '/pagamento/$code'
    | '/painel/certificados'
    | '/painel/pedidos'
    | '/painel/perfil'
    | '/painel/perguntas'
    | '/painel/tentativas'
    | '/painel/wishlist'
    | '/pedido/$code'
    | '/admin/'
    | '/blog/'
    | '/bodyoga/'
    | '/cursos/'
    | '/loja/'
    | '/painel/'
    | '/admin/ajuda/$slug'
    | '/admin/blog/$id'
    | '/admin/bodyoga-slides/$id'
    | '/admin/configuracoes/asaas'
    | '/admin/configuracoes/base'
    | '/admin/configuracoes/cupom'
    | '/admin/configuracoes/diagnosticos'
    | '/admin/configuracoes/emails'
    | '/admin/configuracoes/integracoes'
    | '/admin/configuracoes/melhor-envio'
    | '/admin/configuracoes/mercadopago'
    | '/admin/configuracoes/newsletter'
    | '/admin/configuracoes/site'
    | '/admin/configuracoes/usuarios'
    | '/admin/produtos/$id'
    | '/admin/site/menu'
    | '/api/public/instagram-feed.xml'
    | '/api/public/media'
    | '/painel/aula/$lessonId'
    | '/admin/ajuda/'
    | '/admin/blog/'
    | '/admin/bodyoga-slides/'
    | '/admin/configuracoes/'
    | '/admin/cursos/'
    | '/admin/produtos/'
    | '/admin/site/'
    | '/admin/cursos/$id/aulas'
    | '/admin/cursos/$id/editar'
    | '/admin/cursos/$id/aulas/$lessonId/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendeSuaAulaRoute: typeof AgendeSuaAulaRoute
  BioRoute: typeof BioRoute
  BodyogaRoute: typeof BodyogaRouteWithChildren
  CadastroDeAlunosRoute: typeof CadastroDeAlunosRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  PerfumistaRoute: typeof PerfumistaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  AdminAgendamentosRoute: typeof AdminAgendamentosRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminDiagnosticoEnvioRoute: typeof AdminDiagnosticoEnvioRoute
  AdminDiagnosticoPagamentosRoute: typeof AdminDiagnosticoPagamentosRoute
  AdminDisponibilidadeRoute: typeof AdminDisponibilidadeRoute
  AdminInscritosRoute: typeof AdminInscritosRoute
  AdminNotasFiscaisRoute: typeof AdminNotasFiscaisRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminSocialRoute: typeof AdminSocialRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CertificadoCodeRoute: typeof CertificadoCodeRoute
  CursosSlugRoute: typeof CursosSlugRoute
  LojaSlugRoute: typeof LojaSlugRoute
  PagamentoCodeRoute: typeof PagamentoCodeRoute
  PainelCertificadosRoute: typeof PainelCertificadosRoute
  PainelPedidosRoute: typeof PainelPedidosRoute
  PainelPerfilRoute: typeof PainelPerfilRoute
  PainelPerguntasRoute: typeof PainelPerguntasRoute
  PainelTentativasRoute: typeof PainelTentativasRoute
  PainelWishlistRoute: typeof PainelWishlistRoute
  PedidoCodeRoute: typeof PedidoCodeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CursosIndexRoute: typeof CursosIndexRoute
  LojaIndexRoute: typeof LojaIndexRoute
  PainelIndexRoute: typeof PainelIndexRoute
  AdminAjudaSlugRoute: typeof AdminAjudaSlugRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBodyogaSlidesIdRoute: typeof AdminBodyogaSlidesIdRoute
  AdminConfiguracoesAsaasRoute: typeof AdminConfiguracoesAsaasRoute
  AdminConfiguracoesBaseRoute: typeof AdminConfiguracoesBaseRoute
  AdminConfiguracoesCupomRoute: typeof AdminConfiguracoesCupomRoute
  AdminConfiguracoesDiagnosticosRoute: typeof AdminConfiguracoesDiagnosticosRoute
  AdminConfiguracoesEmailsRoute: typeof AdminConfiguracoesEmailsRoute
  AdminConfiguracoesIntegracoesRoute: typeof AdminConfiguracoesIntegracoesRoute
  AdminConfiguracoesMelhorEnvioRoute: typeof AdminConfiguracoesMelhorEnvioRoute
  AdminConfiguracoesMercadopagoRoute: typeof AdminConfiguracoesMercadopagoRoute
  AdminConfiguracoesNewsletterRoute: typeof AdminConfiguracoesNewsletterRoute
  AdminConfiguracoesSiteRoute: typeof AdminConfiguracoesSiteRoute
  AdminConfiguracoesUsuariosRoute: typeof AdminConfiguracoesUsuariosRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminSiteMenuRoute: typeof AdminSiteMenuRoute
  ApiPublicInstagramFeedDotxmlRoute: typeof ApiPublicInstagramFeedDotxmlRoute
  ApiPublicMediaRoute: typeof ApiPublicMediaRoute
  PainelAulaLessonIdRoute: typeof PainelAulaLessonIdRoute
  AdminAjudaIndexRoute: typeof AdminAjudaIndexRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminBodyogaSlidesIndexRoute: typeof AdminBodyogaSlidesIndexRoute
  AdminConfiguracoesIndexRoute: typeof AdminConfiguracoesIndexRoute
  AdminCursosIndexRoute: typeof AdminCursosIndexRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
  AdminSiteIndexRoute: typeof AdminSiteIndexRoute
  AdminCursosIdAulasRoute: typeof AdminCursosIdAulasRouteWithChildren
  AdminCursosIdEditarRoute: typeof AdminCursosIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfumista': {
      id: '/perfumista'
      path: '/perfumista'
      fullPath: '/perfumista'
      preLoaderRoute: typeof PerfumistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-de-alunos': {
      id: '/cadastro-de-alunos'
      path: '/cadastro-de-alunos'
      fullPath: '/cadastro-de-alunos'
      preLoaderRoute: typeof CadastroDeAlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodyoga': {
      id: '/bodyoga'
      path: '/bodyoga'
      fullPath: '/bodyoga'
      preLoaderRoute: typeof BodyogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agende-sua-aula': {
      id: '/agende-sua-aula'
      path: '/agende-sua-aula'
      fullPath: '/agende-sua-aula'
      preLoaderRoute: typeof AgendeSuaAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/': {
      id: '/loja/'
      path: '/loja'
      fullPath: '/loja/'
      preLoaderRoute: typeof LojaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodyoga/': {
      id: '/bodyoga/'
      path: '/'
      fullPath: '/bodyoga/'
      preLoaderRoute: typeof BodyogaIndexRouteImport
      parentRoute: typeof BodyogaRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$code': {
      id: '/pedido/$code'
      path: '/pedido/$code'
      fullPath: '/pedido/$code'
      preLoaderRoute: typeof PedidoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/wishlist': {
      id: '/painel/wishlist'
      path: '/painel/wishlist'
      fullPath: '/painel/wishlist'
      preLoaderRoute: typeof PainelWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/tentativas': {
      id: '/painel/tentativas'
      path: '/painel/tentativas'
      fullPath: '/painel/tentativas'
      preLoaderRoute: typeof PainelTentativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/perguntas': {
      id: '/painel/perguntas'
      path: '/painel/perguntas'
      fullPath: '/painel/perguntas'
      preLoaderRoute: typeof PainelPerguntasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/perfil': {
      id: '/painel/perfil'
      path: '/painel/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof PainelPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/pedidos': {
      id: '/painel/pedidos'
      path: '/painel/pedidos'
      fullPath: '/painel/pedidos'
      preLoaderRoute: typeof PainelPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/certificados': {
      id: '/painel/certificados'
      path: '/painel/certificados'
      fullPath: '/painel/certificados'
      preLoaderRoute: typeof PainelCertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$code': {
      id: '/pagamento/$code'
      path: '/pagamento/$code'
      fullPath: '/pagamento/$code'
      preLoaderRoute: typeof PagamentoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado/$code': {
      id: '/certificado/$code'
      path: '/certificado/$code'
      fullPath: '/certificado/$code'
      preLoaderRoute: typeof CertificadoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/social': {
      id: '/admin/social'
      path: '/admin/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/admin/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notas-fiscais': {
      id: '/admin/notas-fiscais'
      path: '/admin/notas-fiscais'
      fullPath: '/admin/notas-fiscais'
      preLoaderRoute: typeof AdminNotasFiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inscritos': {
      id: '/admin/inscritos'
      path: '/admin/inscritos'
      fullPath: '/admin/inscritos'
      preLoaderRoute: typeof AdminInscritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/disponibilidade': {
      id: '/admin/disponibilidade'
      path: '/admin/disponibilidade'
      fullPath: '/admin/disponibilidade'
      preLoaderRoute: typeof AdminDisponibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostico-pagamentos': {
      id: '/admin/diagnostico-pagamentos'
      path: '/admin/diagnostico-pagamentos'
      fullPath: '/admin/diagnostico-pagamentos'
      preLoaderRoute: typeof AdminDiagnosticoPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostico-envio': {
      id: '/admin/diagnostico-envio'
      path: '/admin/diagnostico-envio'
      fullPath: '/admin/diagnostico-envio'
      preLoaderRoute: typeof AdminDiagnosticoEnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/admin/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agendamentos': {
      id: '/admin/agendamentos'
      path: '/admin/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AdminAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/site/': {
      id: '/admin/site/'
      path: '/admin/site'
      fullPath: '/admin/site/'
      preLoaderRoute: typeof AdminSiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/admin/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/': {
      id: '/admin/cursos/'
      path: '/admin/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AdminCursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/': {
      id: '/admin/configuracoes/'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes/'
      preLoaderRoute: typeof AdminConfiguracoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bodyoga-slides/': {
      id: '/admin/bodyoga-slides/'
      path: '/admin/bodyoga-slides'
      fullPath: '/admin/bodyoga-slides/'
      preLoaderRoute: typeof AdminBodyogaSlidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ajuda/': {
      id: '/admin/ajuda/'
      path: '/admin/ajuda'
      fullPath: '/admin/ajuda/'
      preLoaderRoute: typeof AdminAjudaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/aula/$lessonId': {
      id: '/painel/aula/$lessonId'
      path: '/painel/aula/$lessonId'
      fullPath: '/painel/aula/$lessonId'
      preLoaderRoute: typeof PainelAulaLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media': {
      id: '/api/public/media'
      path: '/api/public/media'
      fullPath: '/api/public/media'
      preLoaderRoute: typeof ApiPublicMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-feed.xml': {
      id: '/api/public/instagram-feed.xml'
      path: '/api/public/instagram-feed.xml'
      fullPath: '/api/public/instagram-feed.xml'
      preLoaderRoute: typeof ApiPublicInstagramFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/site/menu': {
      id: '/admin/site/menu'
      path: '/admin/site/menu'
      fullPath: '/admin/site/menu'
      preLoaderRoute: typeof AdminSiteMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/admin/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/usuarios': {
      id: '/admin/configuracoes/usuarios'
      path: '/admin/configuracoes/usuarios'
      fullPath: '/admin/configuracoes/usuarios'
      preLoaderRoute: typeof AdminConfiguracoesUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/site': {
      id: '/admin/configuracoes/site'
      path: '/admin/configuracoes/site'
      fullPath: '/admin/configuracoes/site'
      preLoaderRoute: typeof AdminConfiguracoesSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/newsletter': {
      id: '/admin/configuracoes/newsletter'
      path: '/admin/configuracoes/newsletter'
      fullPath: '/admin/configuracoes/newsletter'
      preLoaderRoute: typeof AdminConfiguracoesNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/mercadopago': {
      id: '/admin/configuracoes/mercadopago'
      path: '/admin/configuracoes/mercadopago'
      fullPath: '/admin/configuracoes/mercadopago'
      preLoaderRoute: typeof AdminConfiguracoesMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/melhor-envio': {
      id: '/admin/configuracoes/melhor-envio'
      path: '/admin/configuracoes/melhor-envio'
      fullPath: '/admin/configuracoes/melhor-envio'
      preLoaderRoute: typeof AdminConfiguracoesMelhorEnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/integracoes': {
      id: '/admin/configuracoes/integracoes'
      path: '/admin/configuracoes/integracoes'
      fullPath: '/admin/configuracoes/integracoes'
      preLoaderRoute: typeof AdminConfiguracoesIntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/emails': {
      id: '/admin/configuracoes/emails'
      path: '/admin/configuracoes/emails'
      fullPath: '/admin/configuracoes/emails'
      preLoaderRoute: typeof AdminConfiguracoesEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/diagnosticos': {
      id: '/admin/configuracoes/diagnosticos'
      path: '/admin/configuracoes/diagnosticos'
      fullPath: '/admin/configuracoes/diagnosticos'
      preLoaderRoute: typeof AdminConfiguracoesDiagnosticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/cupom': {
      id: '/admin/configuracoes/cupom'
      path: '/admin/configuracoes/cupom'
      fullPath: '/admin/configuracoes/cupom'
      preLoaderRoute: typeof AdminConfiguracoesCupomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/base': {
      id: '/admin/configuracoes/base'
      path: '/admin/configuracoes/base'
      fullPath: '/admin/configuracoes/base'
      preLoaderRoute: typeof AdminConfiguracoesBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/asaas': {
      id: '/admin/configuracoes/asaas'
      path: '/admin/configuracoes/asaas'
      fullPath: '/admin/configuracoes/asaas'
      preLoaderRoute: typeof AdminConfiguracoesAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bodyoga-slides/$id': {
      id: '/admin/bodyoga-slides/$id'
      path: '/admin/bodyoga-slides/$id'
      fullPath: '/admin/bodyoga-slides/$id'
      preLoaderRoute: typeof AdminBodyogaSlidesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ajuda/$slug': {
      id: '/admin/ajuda/$slug'
      path: '/admin/ajuda/$slug'
      fullPath: '/admin/ajuda/$slug'
      preLoaderRoute: typeof AdminAjudaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/$id/editar': {
      id: '/admin/cursos/$id/editar'
      path: '/admin/cursos/$id/editar'
      fullPath: '/admin/cursos/$id/editar'
      preLoaderRoute: typeof AdminCursosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/$id/aulas': {
      id: '/admin/cursos/$id/aulas'
      path: '/admin/cursos/$id/aulas'
      fullPath: '/admin/cursos/$id/aulas'
      preLoaderRoute: typeof AdminCursosIdAulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/$id/aulas/$lessonId/quiz': {
      id: '/admin/cursos/$id/aulas/$lessonId/quiz'
      path: '/$lessonId/quiz'
      fullPath: '/admin/cursos/$id/aulas/$lessonId/quiz'
      preLoaderRoute: typeof AdminCursosIdAulasLessonIdQuizRouteImport
      parentRoute: typeof AdminCursosIdAulasRoute
    }
  }
}

interface BodyogaRouteChildren {
  BodyogaIndexRoute: typeof BodyogaIndexRoute
}

const BodyogaRouteChildren: BodyogaRouteChildren = {
  BodyogaIndexRoute: BodyogaIndexRoute,
}

const BodyogaRouteWithChildren =
  BodyogaRoute._addFileChildren(BodyogaRouteChildren)

interface AdminCursosIdAulasRouteChildren {
  AdminCursosIdAulasLessonIdQuizRoute: typeof AdminCursosIdAulasLessonIdQuizRoute
}

const AdminCursosIdAulasRouteChildren: AdminCursosIdAulasRouteChildren = {
  AdminCursosIdAulasLessonIdQuizRoute: AdminCursosIdAulasLessonIdQuizRoute,
}

const AdminCursosIdAulasRouteWithChildren =
  AdminCursosIdAulasRoute._addFileChildren(AdminCursosIdAulasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendeSuaAulaRoute: AgendeSuaAulaRoute,
  BioRoute: BioRoute,
  BodyogaRoute: BodyogaRouteWithChildren,
  CadastroDeAlunosRoute: CadastroDeAlunosRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  PerfumistaRoute: PerfumistaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AdminAgendamentosRoute: AdminAgendamentosRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminDiagnosticoEnvioRoute: AdminDiagnosticoEnvioRoute,
  AdminDiagnosticoPagamentosRoute: AdminDiagnosticoPagamentosRoute,
  AdminDisponibilidadeRoute: AdminDisponibilidadeRoute,
  AdminInscritosRoute: AdminInscritosRoute,
  AdminNotasFiscaisRoute: AdminNotasFiscaisRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminSocialRoute: AdminSocialRoute,
  BlogSlugRoute: BlogSlugRoute,
  CertificadoCodeRoute: CertificadoCodeRoute,
  CursosSlugRoute: CursosSlugRoute,
  LojaSlugRoute: LojaSlugRoute,
  PagamentoCodeRoute: PagamentoCodeRoute,
  PainelCertificadosRoute: PainelCertificadosRoute,
  PainelPedidosRoute: PainelPedidosRoute,
  PainelPerfilRoute: PainelPerfilRoute,
  PainelPerguntasRoute: PainelPerguntasRoute,
  PainelTentativasRoute: PainelTentativasRoute,
  PainelWishlistRoute: PainelWishlistRoute,
  PedidoCodeRoute: PedidoCodeRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CursosIndexRoute: CursosIndexRoute,
  LojaIndexRoute: LojaIndexRoute,
  PainelIndexRoute: PainelIndexRoute,
  AdminAjudaSlugRoute: AdminAjudaSlugRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBodyogaSlidesIdRoute: AdminBodyogaSlidesIdRoute,
  AdminConfiguracoesAsaasRoute: AdminConfiguracoesAsaasRoute,
  AdminConfiguracoesBaseRoute: AdminConfiguracoesBaseRoute,
  AdminConfiguracoesCupomRoute: AdminConfiguracoesCupomRoute,
  AdminConfiguracoesDiagnosticosRoute: AdminConfiguracoesDiagnosticosRoute,
  AdminConfiguracoesEmailsRoute: AdminConfiguracoesEmailsRoute,
  AdminConfiguracoesIntegracoesRoute: AdminConfiguracoesIntegracoesRoute,
  AdminConfiguracoesMelhorEnvioRoute: AdminConfiguracoesMelhorEnvioRoute,
  AdminConfiguracoesMercadopagoRoute: AdminConfiguracoesMercadopagoRoute,
  AdminConfiguracoesNewsletterRoute: AdminConfiguracoesNewsletterRoute,
  AdminConfiguracoesSiteRoute: AdminConfiguracoesSiteRoute,
  AdminConfiguracoesUsuariosRoute: AdminConfiguracoesUsuariosRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminSiteMenuRoute: AdminSiteMenuRoute,
  ApiPublicInstagramFeedDotxmlRoute: ApiPublicInstagramFeedDotxmlRoute,
  ApiPublicMediaRoute: ApiPublicMediaRoute,
  PainelAulaLessonIdRoute: PainelAulaLessonIdRoute,
  AdminAjudaIndexRoute: AdminAjudaIndexRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminBodyogaSlidesIndexRoute: AdminBodyogaSlidesIndexRoute,
  AdminConfiguracoesIndexRoute: AdminConfiguracoesIndexRoute,
  AdminCursosIndexRoute: AdminCursosIndexRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
  AdminSiteIndexRoute: AdminSiteIndexRoute,
  AdminCursosIdAulasRoute: AdminCursosIdAulasRouteWithChildren,
  AdminCursosIdEditarRoute: AdminCursosIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
