/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfumistaRouteImport } from './routes/perfumista'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroDeAlunosRouteImport } from './routes/cadastro-de-alunos'
import { Route as BodyogaRouteImport } from './routes/bodyoga'
import { Route as BioRouteImport } from './routes/bio'
import { Route as AgendeSuaAulaRouteImport } from './routes/agende-sua-aula'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as LojaIndexRouteImport } from './routes/loja/index'
import { Route as CursosIndexRouteImport } from './routes/cursos/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PedidoCodeRouteImport } from './routes/pedido/$code'
import { Route as PainelWishlistRouteImport } from './routes/painel/wishlist'
import { Route as PainelTentativasRouteImport } from './routes/painel/tentativas'
import { Route as PainelPerguntasRouteImport } from './routes/painel/perguntas'
import { Route as PainelPerfilRouteImport } from './routes/painel/perfil'
import { Route as PainelPedidosRouteImport } from './routes/painel/pedidos'
import { Route as PainelCertificadosRouteImport } from './routes/painel/certificados'
import { Route as LojaSlugRouteImport } from './routes/loja/$slug'
import { Route as CursosSlugRouteImport } from './routes/cursos/$slug'
import { Route as CertificadoCodeRouteImport } from './routes/certificado/$code'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminInscritosRouteImport } from './routes/admin/inscritos'
import { Route as AdminDisponibilidadeRouteImport } from './routes/admin/disponibilidade'
import { Route as AdminDiagnosticoPagamentosRouteImport } from './routes/admin/diagnostico-pagamentos'
import { Route as AdminDiagnosticoEnvioRouteImport } from './routes/admin/diagnostico-envio'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminBroadcastRouteImport } from './routes/admin/broadcast'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin/avaliacoes'
import { Route as AdminAgendamentosRouteImport } from './routes/admin/agendamentos'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin/produtos/index'
import { Route as AdminCursosIndexRouteImport } from './routes/admin/cursos/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as PainelAulaLessonIdRouteImport } from './routes/painel/aula/$lessonId'
import { Route as AdminProdutosIdRouteImport } from './routes/admin/produtos/$id'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog/$id'
import { Route as AdminCursosIdEditarRouteImport } from './routes/admin/cursos/$id/editar'
import { Route as AdminCursosIdAulasRouteImport } from './routes/admin/cursos/$id/aulas'
import { Route as AdminCursosIdAulasLessonIdQuizRouteImport } from './routes/admin/cursos/$id/aulas/$lessonId/quiz'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumistaRoute = PerfumistaRouteImport.update({
  id: '/perfumista',
  path: '/perfumista',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroDeAlunosRoute = CadastroDeAlunosRouteImport.update({
  id: '/cadastro-de-alunos',
  path: '/cadastro-de-alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyogaRoute = BodyogaRouteImport.update({
  id: '/bodyoga',
  path: '/bodyoga',
  getParentRoute: () => rootRouteImport,
} as any)
const BioRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendeSuaAulaRoute = AgendeSuaAulaRouteImport.update({
  id: '/agende-sua-aula',
  path: '/agende-sua-aula',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIndexRoute = LojaIndexRouteImport.update({
  id: '/loja/',
  path: '/loja/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoCodeRoute = PedidoCodeRouteImport.update({
  id: '/pedido/$code',
  path: '/pedido/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelWishlistRoute = PainelWishlistRouteImport.update({
  id: '/painel/wishlist',
  path: '/painel/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelTentativasRoute = PainelTentativasRouteImport.update({
  id: '/painel/tentativas',
  path: '/painel/tentativas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPerguntasRoute = PainelPerguntasRouteImport.update({
  id: '/painel/perguntas',
  path: '/painel/perguntas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPerfilRoute = PainelPerfilRouteImport.update({
  id: '/painel/perfil',
  path: '/painel/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPedidosRoute = PainelPedidosRouteImport.update({
  id: '/painel/pedidos',
  path: '/painel/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelCertificadosRoute = PainelCertificadosRouteImport.update({
  id: '/painel/certificados',
  path: '/painel/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoCodeRoute = CertificadoCodeRouteImport.update({
  id: '/certificado/$code',
  path: '/certificado/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInscritosRoute = AdminInscritosRouteImport.update({
  id: '/admin/inscritos',
  path: '/admin/inscritos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisponibilidadeRoute = AdminDisponibilidadeRouteImport.update({
  id: '/admin/disponibilidade',
  path: '/admin/disponibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticoPagamentosRoute =
  AdminDiagnosticoPagamentosRouteImport.update({
    id: '/admin/diagnostico-pagamentos',
    path: '/admin/diagnostico-pagamentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDiagnosticoEnvioRoute = AdminDiagnosticoEnvioRouteImport.update({
  id: '/admin/diagnostico-envio',
  path: '/admin/diagnostico-envio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/admin/broadcast',
  path: '/admin/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/admin/avaliacoes',
  path: '/admin/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgendamentosRoute = AdminAgendamentosRouteImport.update({
  id: '/admin/agendamentos',
  path: '/admin/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/admin/produtos/',
  path: '/admin/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIndexRoute = AdminCursosIndexRouteImport.update({
  id: '/admin/cursos/',
  path: '/admin/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAulaLessonIdRoute = PainelAulaLessonIdRouteImport.update({
  id: '/painel/aula/$lessonId',
  path: '/painel/aula/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/admin/produtos/$id',
  path: '/admin/produtos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/admin/blog/$id',
  path: '/admin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIdEditarRoute = AdminCursosIdEditarRouteImport.update({
  id: '/admin/cursos/$id/editar',
  path: '/admin/cursos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIdAulasRoute = AdminCursosIdAulasRouteImport.update({
  id: '/admin/cursos/$id/aulas',
  path: '/admin/cursos/$id/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIdAulasLessonIdQuizRoute =
  AdminCursosIdAulasLessonIdQuizRouteImport.update({
    id: '/$lessonId/quiz',
    path: '/$lessonId/quiz',
    getParentRoute: () => AdminCursosIdAulasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agende-sua-aula': typeof AgendeSuaAulaRoute
  '/bio': typeof BioRoute
  '/bodyoga': typeof BodyogaRoute
  '/cadastro-de-alunos': typeof CadastroDeAlunosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/perfumista': typeof PerfumistaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/diagnostico-envio': typeof AdminDiagnosticoEnvioRoute
  '/admin/diagnostico-pagamentos': typeof AdminDiagnosticoPagamentosRoute
  '/admin/disponibilidade': typeof AdminDisponibilidadeRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificado/$code': typeof CertificadoCodeRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/painel/certificados': typeof PainelCertificadosRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/perguntas': typeof PainelPerguntasRoute
  '/painel/tentativas': typeof PainelTentativasRoute
  '/painel/wishlist': typeof PainelWishlistRoute
  '/pedido/$code': typeof PedidoCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/painel/aula/$lessonId': typeof PainelAulaLessonIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/admin/cursos/$id/aulas': typeof AdminCursosIdAulasRouteWithChildren
  '/admin/cursos/$id/editar': typeof AdminCursosIdEditarRoute
  '/admin/cursos/$id/aulas/$lessonId/quiz': typeof AdminCursosIdAulasLessonIdQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agende-sua-aula': typeof AgendeSuaAulaRoute
  '/bio': typeof BioRoute
  '/bodyoga': typeof BodyogaRoute
  '/cadastro-de-alunos': typeof CadastroDeAlunosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/perfumista': typeof PerfumistaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/diagnostico-envio': typeof AdminDiagnosticoEnvioRoute
  '/admin/diagnostico-pagamentos': typeof AdminDiagnosticoPagamentosRoute
  '/admin/disponibilidade': typeof AdminDisponibilidadeRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificado/$code': typeof CertificadoCodeRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/painel/certificados': typeof PainelCertificadosRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/perguntas': typeof PainelPerguntasRoute
  '/painel/tentativas': typeof PainelTentativasRoute
  '/painel/wishlist': typeof PainelWishlistRoute
  '/pedido/$code': typeof PedidoCodeRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/cursos': typeof CursosIndexRoute
  '/loja': typeof LojaIndexRoute
  '/painel': typeof PainelIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/painel/aula/$lessonId': typeof PainelAulaLessonIdRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/cursos': typeof AdminCursosIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/admin/cursos/$id/aulas': typeof AdminCursosIdAulasRouteWithChildren
  '/admin/cursos/$id/editar': typeof AdminCursosIdEditarRoute
  '/admin/cursos/$id/aulas/$lessonId/quiz': typeof AdminCursosIdAulasLessonIdQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agende-sua-aula': typeof AgendeSuaAulaRoute
  '/bio': typeof BioRoute
  '/bodyoga': typeof BodyogaRoute
  '/cadastro-de-alunos': typeof CadastroDeAlunosRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/perfumista': typeof PerfumistaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/diagnostico-envio': typeof AdminDiagnosticoEnvioRoute
  '/admin/diagnostico-pagamentos': typeof AdminDiagnosticoPagamentosRoute
  '/admin/disponibilidade': typeof AdminDisponibilidadeRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificado/$code': typeof CertificadoCodeRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/painel/certificados': typeof PainelCertificadosRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/perguntas': typeof PainelPerguntasRoute
  '/painel/tentativas': typeof PainelTentativasRoute
  '/painel/wishlist': typeof PainelWishlistRoute
  '/pedido/$code': typeof PedidoCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cursos/': typeof CursosIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/painel/aula/$lessonId': typeof PainelAulaLessonIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/admin/cursos/$id/aulas': typeof AdminCursosIdAulasRouteWithChildren
  '/admin/cursos/$id/editar': typeof AdminCursosIdEditarRoute
  '/admin/cursos/$id/aulas/$lessonId/quiz': typeof AdminCursosIdAulasLessonIdQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agende-sua-aula'
    | '/bio'
    | '/bodyoga'
    | '/cadastro-de-alunos'
    | '/carrinho'
    | '/checkout'
    | '/login'
    | '/perfumista'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/agendamentos'
    | '/admin/avaliacoes'
    | '/admin/broadcast'
    | '/admin/configuracoes'
    | '/admin/diagnostico-envio'
    | '/admin/diagnostico-pagamentos'
    | '/admin/disponibilidade'
    | '/admin/inscritos'
    | '/admin/pedidos'
    | '/blog/$slug'
    | '/certificado/$code'
    | '/cursos/$slug'
    | '/loja/$slug'
    | '/painel/certificados'
    | '/painel/pedidos'
    | '/painel/perfil'
    | '/painel/perguntas'
    | '/painel/tentativas'
    | '/painel/wishlist'
    | '/pedido/$code'
    | '/admin/'
    | '/blog/'
    | '/cursos/'
    | '/loja/'
    | '/painel/'
    | '/admin/blog/$id'
    | '/admin/produtos/$id'
    | '/painel/aula/$lessonId'
    | '/admin/blog/'
    | '/admin/cursos/'
    | '/admin/produtos/'
    | '/admin/cursos/$id/aulas'
    | '/admin/cursos/$id/editar'
    | '/admin/cursos/$id/aulas/$lessonId/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agende-sua-aula'
    | '/bio'
    | '/bodyoga'
    | '/cadastro-de-alunos'
    | '/carrinho'
    | '/checkout'
    | '/login'
    | '/perfumista'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/agendamentos'
    | '/admin/avaliacoes'
    | '/admin/broadcast'
    | '/admin/configuracoes'
    | '/admin/diagnostico-envio'
    | '/admin/diagnostico-pagamentos'
    | '/admin/disponibilidade'
    | '/admin/inscritos'
    | '/admin/pedidos'
    | '/blog/$slug'
    | '/certificado/$code'
    | '/cursos/$slug'
    | '/loja/$slug'
    | '/painel/certificados'
    | '/painel/pedidos'
    | '/painel/perfil'
    | '/painel/perguntas'
    | '/painel/tentativas'
    | '/painel/wishlist'
    | '/pedido/$code'
    | '/admin'
    | '/blog'
    | '/cursos'
    | '/loja'
    | '/painel'
    | '/admin/blog/$id'
    | '/admin/produtos/$id'
    | '/painel/aula/$lessonId'
    | '/admin/blog'
    | '/admin/cursos'
    | '/admin/produtos'
    | '/admin/cursos/$id/aulas'
    | '/admin/cursos/$id/editar'
    | '/admin/cursos/$id/aulas/$lessonId/quiz'
  id:
    | '__root__'
    | '/'
    | '/agende-sua-aula'
    | '/bio'
    | '/bodyoga'
    | '/cadastro-de-alunos'
    | '/carrinho'
    | '/checkout'
    | '/login'
    | '/perfumista'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/admin/agendamentos'
    | '/admin/avaliacoes'
    | '/admin/broadcast'
    | '/admin/configuracoes'
    | '/admin/diagnostico-envio'
    | '/admin/diagnostico-pagamentos'
    | '/admin/disponibilidade'
    | '/admin/inscritos'
    | '/admin/pedidos'
    | '/blog/$slug'
    | '/certificado/$code'
    | '/cursos/$slug'
    | '/loja/$slug'
    | '/painel/certificados'
    | '/painel/pedidos'
    | '/painel/perfil'
    | '/painel/perguntas'
    | '/painel/tentativas'
    | '/painel/wishlist'
    | '/pedido/$code'
    | '/admin/'
    | '/blog/'
    | '/cursos/'
    | '/loja/'
    | '/painel/'
    | '/admin/blog/$id'
    | '/admin/produtos/$id'
    | '/painel/aula/$lessonId'
    | '/admin/blog/'
    | '/admin/cursos/'
    | '/admin/produtos/'
    | '/admin/cursos/$id/aulas'
    | '/admin/cursos/$id/editar'
    | '/admin/cursos/$id/aulas/$lessonId/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendeSuaAulaRoute: typeof AgendeSuaAulaRoute
  BioRoute: typeof BioRoute
  BodyogaRoute: typeof BodyogaRoute
  CadastroDeAlunosRoute: typeof CadastroDeAlunosRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  PerfumistaRoute: typeof PerfumistaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  AdminAgendamentosRoute: typeof AdminAgendamentosRoute
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDiagnosticoEnvioRoute: typeof AdminDiagnosticoEnvioRoute
  AdminDiagnosticoPagamentosRoute: typeof AdminDiagnosticoPagamentosRoute
  AdminDisponibilidadeRoute: typeof AdminDisponibilidadeRoute
  AdminInscritosRoute: typeof AdminInscritosRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CertificadoCodeRoute: typeof CertificadoCodeRoute
  CursosSlugRoute: typeof CursosSlugRoute
  LojaSlugRoute: typeof LojaSlugRoute
  PainelCertificadosRoute: typeof PainelCertificadosRoute
  PainelPedidosRoute: typeof PainelPedidosRoute
  PainelPerfilRoute: typeof PainelPerfilRoute
  PainelPerguntasRoute: typeof PainelPerguntasRoute
  PainelTentativasRoute: typeof PainelTentativasRoute
  PainelWishlistRoute: typeof PainelWishlistRoute
  PedidoCodeRoute: typeof PedidoCodeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CursosIndexRoute: typeof CursosIndexRoute
  LojaIndexRoute: typeof LojaIndexRoute
  PainelIndexRoute: typeof PainelIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  PainelAulaLessonIdRoute: typeof PainelAulaLessonIdRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCursosIndexRoute: typeof AdminCursosIndexRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
  AdminCursosIdAulasRoute: typeof AdminCursosIdAulasRouteWithChildren
  AdminCursosIdEditarRoute: typeof AdminCursosIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfumista': {
      id: '/perfumista'
      path: '/perfumista'
      fullPath: '/perfumista'
      preLoaderRoute: typeof PerfumistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-de-alunos': {
      id: '/cadastro-de-alunos'
      path: '/cadastro-de-alunos'
      fullPath: '/cadastro-de-alunos'
      preLoaderRoute: typeof CadastroDeAlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodyoga': {
      id: '/bodyoga'
      path: '/bodyoga'
      fullPath: '/bodyoga'
      preLoaderRoute: typeof BodyogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agende-sua-aula': {
      id: '/agende-sua-aula'
      path: '/agende-sua-aula'
      fullPath: '/agende-sua-aula'
      preLoaderRoute: typeof AgendeSuaAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/': {
      id: '/loja/'
      path: '/loja'
      fullPath: '/loja/'
      preLoaderRoute: typeof LojaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$code': {
      id: '/pedido/$code'
      path: '/pedido/$code'
      fullPath: '/pedido/$code'
      preLoaderRoute: typeof PedidoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/wishlist': {
      id: '/painel/wishlist'
      path: '/painel/wishlist'
      fullPath: '/painel/wishlist'
      preLoaderRoute: typeof PainelWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/tentativas': {
      id: '/painel/tentativas'
      path: '/painel/tentativas'
      fullPath: '/painel/tentativas'
      preLoaderRoute: typeof PainelTentativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/perguntas': {
      id: '/painel/perguntas'
      path: '/painel/perguntas'
      fullPath: '/painel/perguntas'
      preLoaderRoute: typeof PainelPerguntasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/perfil': {
      id: '/painel/perfil'
      path: '/painel/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof PainelPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/pedidos': {
      id: '/painel/pedidos'
      path: '/painel/pedidos'
      fullPath: '/painel/pedidos'
      preLoaderRoute: typeof PainelPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/certificados': {
      id: '/painel/certificados'
      path: '/painel/certificados'
      fullPath: '/painel/certificados'
      preLoaderRoute: typeof PainelCertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado/$code': {
      id: '/certificado/$code'
      path: '/certificado/$code'
      fullPath: '/certificado/$code'
      preLoaderRoute: typeof CertificadoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inscritos': {
      id: '/admin/inscritos'
      path: '/admin/inscritos'
      fullPath: '/admin/inscritos'
      preLoaderRoute: typeof AdminInscritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/disponibilidade': {
      id: '/admin/disponibilidade'
      path: '/admin/disponibilidade'
      fullPath: '/admin/disponibilidade'
      preLoaderRoute: typeof AdminDisponibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostico-pagamentos': {
      id: '/admin/diagnostico-pagamentos'
      path: '/admin/diagnostico-pagamentos'
      fullPath: '/admin/diagnostico-pagamentos'
      preLoaderRoute: typeof AdminDiagnosticoPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostico-envio': {
      id: '/admin/diagnostico-envio'
      path: '/admin/diagnostico-envio'
      fullPath: '/admin/diagnostico-envio'
      preLoaderRoute: typeof AdminDiagnosticoEnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/admin/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/admin/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agendamentos': {
      id: '/admin/agendamentos'
      path: '/admin/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AdminAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/admin/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/': {
      id: '/admin/cursos/'
      path: '/admin/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AdminCursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/aula/$lessonId': {
      id: '/painel/aula/$lessonId'
      path: '/painel/aula/$lessonId'
      fullPath: '/painel/aula/$lessonId'
      preLoaderRoute: typeof PainelAulaLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/admin/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/$id/editar': {
      id: '/admin/cursos/$id/editar'
      path: '/admin/cursos/$id/editar'
      fullPath: '/admin/cursos/$id/editar'
      preLoaderRoute: typeof AdminCursosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/$id/aulas': {
      id: '/admin/cursos/$id/aulas'
      path: '/admin/cursos/$id/aulas'
      fullPath: '/admin/cursos/$id/aulas'
      preLoaderRoute: typeof AdminCursosIdAulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/$id/aulas/$lessonId/quiz': {
      id: '/admin/cursos/$id/aulas/$lessonId/quiz'
      path: '/$lessonId/quiz'
      fullPath: '/admin/cursos/$id/aulas/$lessonId/quiz'
      preLoaderRoute: typeof AdminCursosIdAulasLessonIdQuizRouteImport
      parentRoute: typeof AdminCursosIdAulasRoute
    }
  }
}

interface AdminCursosIdAulasRouteChildren {
  AdminCursosIdAulasLessonIdQuizRoute: typeof AdminCursosIdAulasLessonIdQuizRoute
}

const AdminCursosIdAulasRouteChildren: AdminCursosIdAulasRouteChildren = {
  AdminCursosIdAulasLessonIdQuizRoute: AdminCursosIdAulasLessonIdQuizRoute,
}

const AdminCursosIdAulasRouteWithChildren =
  AdminCursosIdAulasRoute._addFileChildren(AdminCursosIdAulasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendeSuaAulaRoute: AgendeSuaAulaRoute,
  BioRoute: BioRoute,
  BodyogaRoute: BodyogaRoute,
  CadastroDeAlunosRoute: CadastroDeAlunosRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  PerfumistaRoute: PerfumistaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AdminAgendamentosRoute: AdminAgendamentosRoute,
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDiagnosticoEnvioRoute: AdminDiagnosticoEnvioRoute,
  AdminDiagnosticoPagamentosRoute: AdminDiagnosticoPagamentosRoute,
  AdminDisponibilidadeRoute: AdminDisponibilidadeRoute,
  AdminInscritosRoute: AdminInscritosRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  BlogSlugRoute: BlogSlugRoute,
  CertificadoCodeRoute: CertificadoCodeRoute,
  CursosSlugRoute: CursosSlugRoute,
  LojaSlugRoute: LojaSlugRoute,
  PainelCertificadosRoute: PainelCertificadosRoute,
  PainelPedidosRoute: PainelPedidosRoute,
  PainelPerfilRoute: PainelPerfilRoute,
  PainelPerguntasRoute: PainelPerguntasRoute,
  PainelTentativasRoute: PainelTentativasRoute,
  PainelWishlistRoute: PainelWishlistRoute,
  PedidoCodeRoute: PedidoCodeRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CursosIndexRoute: CursosIndexRoute,
  LojaIndexRoute: LojaIndexRoute,
  PainelIndexRoute: PainelIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  PainelAulaLessonIdRoute: PainelAulaLessonIdRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCursosIndexRoute: AdminCursosIndexRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
  AdminCursosIdAulasRoute: AdminCursosIdAulasRouteWithChildren,
  AdminCursosIdEditarRoute: AdminCursosIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
