// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwxaeckgpypvjiglorto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3eGFlY2tncHlwdmppZ2xvcnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3NDA3ODIsImV4cCI6MjA5NTMxNjc4Mn0.cInQFQ_PuQhKuSWjkqnz5H5oJf4ghDh11yBL1jfDAfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});